site_name: EmbStract
theme: readthedocs
docs_dir: ../../
site_dir: ../../build/docs

plugins:
  - search
  - same-dir
  - mkdocstrings:
      handlers: 
        python:
          paths: [../clang_format/run_clang_format.py]

markdown_extensions:
  - extra
  - admonition
  - pymdownx.snippets:
      auto_append:
        - docs/includes/acronyms.md

exclude_docs: |
  .*
  !docs
  !code

nav:
  - README.md
  - docs/arch/architecture.md
  - Development :
    - Tools: 
      - Installation: docs/dev/tools.md
      - tools/pclint/docs/pclint.md
      - tools/clang_format/docs/clang_format.md
      - tools/clang_tidy/docs/clang_tidy.md
    - docs/dev/folder_structure.md
  - Contributing: 
    - License: LICENSE.md
    - Contributing: CONTRIBUTING.md
    - Contributor License Agreement: CLA.md
    - docs/dev/copyright.md