site_name: EmbStracto
theme: readthedocs
docs_dir: ../../../
site_dir: ../../../build/docs

plugins:
  - search
  - same-dir
  - with-pdf

markdown_extensions:
  - extra
  - admonition
  - pymdownx.snippets:
      auto_append:
        - docs/includes/acronyms.md

exclude_docs: |
  .*
  !docs
  !code

nav:
  - README.md
  - docs/arch/architecture.md
  - Development :
    - docs/dev/tools.md
    - docs/dev/folder_structure.md
  - Contributing: 
    - License: LICENSE.md
    - Contributing: CONTRIBUTING.md
    - Contributor License Agreement: CLA.md
    - docs/dev/copyright.md